### ISSUE TITLE
UnboundLocalError: local variable 'driver' referenced before assignment

### ISSUE THREAD

**Issue by zx2214008** [StreamAlpha/tvdatafeed#26]
Could anyone help with this problem? Following is my code and it keep showing the error.

```
from tvDatafeed import TvDatafeed, Interval

username = 'myuser'
password = 'mypassword'

tv = TvDatafeed(username, password, chromedriver_path=None)
tv = TvDatafeed(auto_login=False)
tv.get_hist('AAPL', 'NASDAQ', interval=Interval.in_5_minute)
```

The error log in following,

```
Traceback (most recent call last):
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\site-packages\tvDatafeed\main.py", line 248, in __webdriver_init
    driver = webdriver.Chrome(
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1360, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 565, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\36900\PycharmProjects\TradingViewAPI\data.py", line 8, in <module>
    tv = TvDatafeed(username, password, chromedriver_path=None)
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\site-packages\tvDatafeed\main.py", line 137, in __init__
    token = self.auth(username, password)
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\site-packages\tvDatafeed\main.py", line 212, in auth
    driver = self.__login(username, password)
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\site-packages\tvDatafeed\main.py", line 152, in __login
    driver = self.__webdriver_init()
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\site-packages\tvDatafeed\main.py", line 260, in __webdriver_init
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment

Process finished with exit code 1
```

**Comment by StreamAlpha** [comment]
install latest version and do manual login

**Comment by zx2214008** [comment]
Thanks a lot for your reply!
I updated the latest version as 1.1.0 and do manual login, but it still showing the same error as following

```
You need to login manually

 Press 'enter' to open the browser 


opening browser. Press enter once lgged in return back and press 'enter'. 

DO NOT CLOSE THE BROWSER
Traceback (most recent call last):
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\site-packages\tvDatafeed\main.py", line 248, in __webdriver_init
    driver = webdriver.Chrome(
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1360, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 565, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\36900\PycharmProjects\TradingViewAPI\data.py", line 11, in <module>
    tv = TvDatafeed(auto_login=False)
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\site-packages\tvDatafeed\main.py", line 137, in __init__
    token = self.auth(username, password)
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\site-packages\tvDatafeed\main.py", line 212, in auth
    driver = self.__login(username, password)
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\site-packages\tvDatafeed\main.py", line 152, in __login
    driver = self.__webdriver_init()
  File "C:\Users\36900\AppData\Local\Programs\Python\Python39\lib\site-packages\tvDatafeed\main.py", line 260, in __webdriver_init
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment
```

**Comment by EnriqueGautoSand** [comment]
same problem,where is the chromedriver path that  autoinstall when install tvdatafeed using pip?

**Comment by kairon007** [comment]
Still getting the same issue with version 1.1.0

**Comment by chetankatke** [comment]
same problem error is about permission
PermissionError: [Errno 13] Permission denied: '/home/ru/.tv_datafeed/'

During handling of the above exception, another exception occurred:

**Comment by kairon007** [comment]
Ditto

**Comment by StreamAlpha** [comment]
on linux I am able to run with following steps-

- install from `hotfix` branch using 
`pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git@hotfix
`

- install chromium browser and chromium chromedriver using `sudo snap install chromium`  `sudo apt-get install chromium-chromedriver`
- locate chrome driver using `whereis chromedriver`  in my case path was `/usr/bin/chromedriver`
- now for the first time use init tvdatafeed with manual login and chromedriver_path 
`tv=TvDatafeed(auto_login=False, chromedriver_path='/usr/bin/chromedriver')`
use path from previous step

- for manual login guide check [this video](https://www.youtube.com/watch?v=f76dOZW2gwI)

hope this helps.

also can someone try installing hotfix on mac if this hotfix helps

**Comment by kairon007** [comment]
@StreamAlpha Tried above still getting following response

> `Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/Users/amit/.tv_datafeed/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tvDatafeed/main.py", line 248, in __webdriver_init
    driver = webdriver.Chrome(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: '' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/amit/PycharmProjects/algo_zero/miscstuff.py", line 1142, in <module>
    customSearch(dataSource=DataSource.TRADING_VIEW, names=constants.fivepaisacomplete,
  File "/Users/amit/PycharmProjects/algo_zero/miscstuff.py", line 1064, in customSearch
    dfList = Repository.getDailyHistoricalData(dataSource=dataSource, stockNamesList=constants.fivepaisacomplete,
  File "/Users/amit/PycharmProjects/algo_zero/models/Repository.py", line 115, in getDailyHistoricalData
    tv = TvDatafeed(auto_login=False,chromedriver_path=chrome_driver_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tvDatafeed/main.py", line 137, in __init__
    token = self.auth(username, password)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tvDatafeed/main.py", line 212, in auth
    driver = self.__login(username, password)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tvDatafeed/main.py", line 152, in __login
    driver = self.__webdriver_init()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tvDatafeed/main.py", line 260, in __webdriver_init
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment`

**Comment by StreamAlpha** [comment]
remove '/Users/amit/.tv_datafeed' dir and try again

**Comment by kairon007** [comment]
removing the above folder worked , the browser opened and the authentication was done, despite that I get the message "you are using nologin method, data you access may be limited" @StreamAlpha

**Comment by chetankatke** [comment]
> on linux I am able to run with following steps-
> 
> * remove .tv_datafeed dir from home
> * install from `hotfix` branch using
>   `pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git@hotfix `
> * install chromium browser and chromium chromedriver using `sudo snap install chromium`  `sudo apt-get install chromium-chromedriver`
> * locate chrome driver using `whereis chromedriver`  in my case path was `/usr/bin/chromedriver`
> * now for the first time use init tvdatafeed with manual login and chromedriver_path
>   `tv=TvDatafeed(auto_login=False, chromedriver_path='/usr/bin/chromedriver')`
>   use path from previous step
> * for manual login guide check [this video](https://www.youtube.com/watch?v=f76dOZW2gwI)
> 
> hope this helps.
> 
> also can someone try installing hotfix on mac if this hotfix helps

Still same problem

**Comment by chetankatke** [comment]
sorry sir problem solved 
i forgot to switch the conda env
now working

**Comment by StreamAlpha** [comment]
so, is this issue resolved for both linux as well as mac?
If yes feel free to close

**Comment by chetankatke** [comment]
> so, is this issue resolved for both linux as well as mac?
> If yes feel free to close

issue is resolved with hotfix for linux
dont know about mac

**Comment by hz7451** [comment]
Does anyone have solution for this issue , I have been stuck for quite a while . Tried both for windows and Mac OS, still have the same issue.

**Comment by Shreevish** [comment]
install chromium browser and chromium chromedriver using sudo snap install chromium sudo apt-get install chromium-chromedriver

How will I perform the above step

**Comment by vennelakantis** [comment]
Removed .tvdatafeed folder, it gets installed while running py file in vs code. I am getting a message for installing chromedriver with y/n. Whether yes or no it is installing .tvdatafeed folder in users/mypc/ and throwing same error. I  am using windows10. ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\anaconda3\envs\tv\lib\site-packages\tvDatafeed\main.py in __webdriver_init(self)
    261 
--> 262             driver = webdriver.Chrome(
    263                 self.chromedriver_path, desired_capabilities=caps, options=options

~\anaconda3\envs\tv\lib\site-packages\selenium\webdriver\chrome\webdriver.py in __init__(self, executable_path, port, options, service_args, desired_capabilities, service_log_path, chrome_options, service, keep_alive)
     68 
---> 69         super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
     70                                         port, options,

~\anaconda3\envs\tv\lib\site-packages\selenium\webdriver\chromium\webdriver.py in __init__(self, browser_name, vendor_prefix, port, options, service_args, desired_capabilities, service_log_path, service, keep_alive)
     89         self.service = service
---> 90         self.service.start()
     91 

~\anaconda3\envs\tv\lib\site-packages\selenium\webdriver\common\service.py in start(self)
     73             cmd.extend(self.command_line_args())
---> 74             self.process = subprocess.Popen(cmd, env=self.env,
     75                                             close_fds=system() != 'Windows',

~\anaconda3\envs\tv\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    857 
--> 858             self._execute_child(args, executable, preexec_fn, close_fds,
    859                                 pass_fds, cwd, env,

~\anaconda3\envs\tv\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1250             else:
-> 1251                 args = list2cmdline(args)
   1252 

~\anaconda3\envs\tv\lib\subprocess.py in list2cmdline(seq)
    552     needquote = False
--> 553     for arg in map(os.fsdecode, seq):
    554         bs_buf = []

~\anaconda3\envs\tv\lib\os.py in fsdecode(filename)
    817         """
--> 818         filename = fspath(filename)  # Does type-checking of `filename`.
    819         if isinstance(filename, bytes):

TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

UnboundLocalError                         Traceback (most recent call last)
c:\Users\Lenovo\tvdata.py in <module>
      3 from tvDatafeed import TvDatafeed, Interval
      4 
----> 5 tv = TvDatafeed(auto_login=False)

~\anaconda3\envs\tv\lib\site-packages\tvDatafeed\main.py in __init__(self, username, password, chromedriver_path, auto_login)
    137 
    138         token = None
--> 139         token = self.auth(username, password)
    140 
    141         if token is None:

~\anaconda3\envs\tv\lib\site-packages\tvDatafeed\main.py in auth(self, username, password)
    212 
    213         else:
--> 214             driver = self.__login(username, password)
    215             if driver is not None:
    216                 token = self.__get_token(driver)

~\anaconda3\envs\tv\lib\site-packages\tvDatafeed\main.py in __login(self, username, password)
    152     def __login(self, username, password):
    153 
--> 154         driver = self.__webdriver_init()
    155 
    156         if not self.__automatic_login:

~\anaconda3\envs\tv\lib\site-packages\tvDatafeed\main.py in __webdriver_init(self)
    272 
    273         except Exception as e:
--> 274             driver.quit()
    275             logger.error(e)
    276 

UnboundLocalError: local variable 'driver' referenced before assignment

**Comment by StreamAlpha** [comment]
check this out- https://youtu.be/kENccs0CW18

However in next release I will try out to simplify manual login process

**Comment by vennelakantis** [comment]
Thank you sir. Worked

**Comment by vennelakantis** [comment]
> check this out- https://youtu.be/kENccs0CW18
> 
> However in next release I will try to simplify manual login procedure

Thank you Sir, it is working now.

**Comment by Shreevish** [comment]
PS C:\Users\vishal\Desktop\tv_tutorials> & c:/Users/vishal/Desktop/tv_tutorials/tvEnv/Scripts/Activate.ps1
& : File C:\Users\vishal\Desktop\tv_tutorials\tvEnv\Scripts\Activate.ps1 cannot be loaded because running scripts is disabled on this system. 
For more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ & c:/Users/vishal/Desktop/tv_tutorials/tvEnv/Scripts/Activate.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\Users\vishal\Desktop\tv_tutorials>

**Comment by AlexSever** [comment]
> check this out- https://youtu.be/kENccs0CW18
> 
> However in next release I will try to simplify manual login procedure

Hello! I tried to follow the video, but it didn't fix the issue for me. I am using `pyenv` (not sure if that matters) to install `python 3.9.8` and then follow the steps in video. I am on MacOS. 
So, after installing the chromedriver (answering "y" in code editor) and pressing enter, browser window opens, but it doesn't direct to tradingview and I get the error message: "UnboundLocalError: local variable 'driver' referenced before assignment"

Any updates on resolving the issue? Also, should I try to do it on Windows 10 instead of MacOS?

**Comment by Djangu-algo** [comment]
AlexServer, try using the following code
```
import logging
logging.basicConfig(level=logging.DEBUG)
```

and see if there is a reference to the chromedriver.exe (I'm using Windows example here, but may be also applicable to MacOS). The debug messages may show that tvDatafeed stores its own copy of the driver somewhere (on Windows it is in the C:\Users\ _Username_\\.tvdatafeed).

The issue on Windows systems is that the driver in the above mentioned directory has to be updated by simply downloading the current version of the chromedriver and overwriting the file in this directory with the new version.

**Comment by AshkanForootan** [comment]
> Does anyone have solution for this issue , I have been stuck for quite a while . Tried both for windows and Mac OS, still have the same issue.
> 
> Update(Window OS): Removed ".tvdatafeed" directory and run again fixed the issue

deleting  ".tvdatafeed" directory fixed my problem.

**Comment by AshkanForootan** [comment]
hello
thank you for this useful program.
can we use it with a "start date" and "end date" instead of number of bars?

**Comment by imjonathan** [comment]
on a mac in place of:
install chromium browser and chromium chromedriver using `sudo snap install chromium sudo apt-get install chromium-chromedriver`

I had to:
`brew install --cask chromium`
`pip install chromedriver`

then it worked.

**Comment by EwertonAvlis** [comment]
Hi
when I make an order for an index value. I have this problem:  ValueError: could not convert string to float: '}'

-----------------------------------------------------

c:\Users\tonya\Desktop\Ciclos\TV_Download_data.ipynb Célula: 4 in <cell line: 4>()
      [1](vscode-notebook-cell:/c%3A/Users/tonya/Desktop/Ciclos/TV_Download_data.ipynb#ch0000003?line=0) #nifty_index_data = tv.get_hist(symbol=Equities_Index[0][0],exchange=Equities_Index[0][1],interval=Interval.in_weekly,n_bars=100,fut_contract=1)
      [2](vscode-notebook-cell:/c%3A/Users/tonya/Desktop/Ciclos/TV_Download_data.ipynb#ch0000003?line=1) # futures continuous contract
----> [4](vscode-notebook-cell:/c%3A/Users/tonya/Desktop/Ciclos/TV_Download_data.ipynb#ch0000003?line=3) nifty_index_data  = tv.get_hist(symbol='NIFTY',exchange='NSE', interval=Interval.in_weekly,n_bars=100,fut_contract=None)

File c:\Users\tonya\AppData\Local\Programs\Python\Python310\lib\site-packages\tvDatafeed\main.py:504, in TvDatafeed.get_hist(self, symbol, exchange, interval, n_bars, fut_contract, extended_session)
    501     if "series_completed" in result:
    502         break
--> 504 return self.__create_df(raw_data, symbol)

File c:\Users\tonya\AppData\Local\Programs\Python\Python310\lib\site-packages\tvDatafeed\main.py:376, in TvDatafeed.__create_df(raw_data, symbol)
    367     xi = re.split("\[|:|,|\]", xi)
    368     ts = datetime.datetime.fromtimestamp(float(xi[4]))
    369     data.append(
    370         [
    371             ts,
    372             float(xi[5]),
    373             float(xi[6]),
    374             float(xi[7]),
    375             float(xi[8]),
--> 376             float(xi[9]),
    377         ]
    378     )
...
    381     data, columns=["datetime", "open", "high", "low", "close", "volume"]
    382 ).set_index("datetime")
    383 data.insert(0, "symbol", value=symbol)

ValueError: could not convert string to float: '}'

**Comment by StreamAlpha** [comment]
fixed in the latest release. install from github

**Comment by EwertonAvlis** [comment]
I fixed it by changing float(x[9]) -> x[9], after knowing that the problem
was in Volume's values.
I will install the latest release.  The tvdatafeed was very helpful. Thanks
for everything.

Best regards

Em sáb., 6 de ago. de 2022 às 16:28, StreamAlpha ***@***.***>
escreveu:
